var nodes = new vis.DataSet([
                             /* {id: a, label: b, ...}, */
{id: '0', label: 'A7\nDEFINE', color: '#31b0d5', title: 'Name: A7<br>Alias: null<br>Value: DEFINE<br>Type: CELL_WITH_FORMULA<br>Id: 0<br>Formula Expression: Formula String: DEFINE(C2, VALUE, B2, A2, VALUE); Formula Values: DEFINE($1800, #, $1500, $1000, DEVDEF_1); Formula Ptg: ; Ptgs:  Index in Ptgs: 0 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '2', label: 'VALUE\nDEVDEF_1', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: DEVDEF_1<br>Type: CONSTANT_VALUE<br>Id: 2<br>Formula Expression: Formula String: VALUE; Formula Values: DEVDEF_1; Formula Ptg: DEVDEF_1; Ptgs: VALUE Index in Ptgs: 1 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '3', label: 'A2\n$1000', color: '#31b0d5', title: 'Name: A2<br>Alias: null<br>Value: $1000<br>Type: CELL_WITH_VALUE<br>Id: 3<br>Formula Expression: Formula String: A2; Formula Values: $1000; Formula Ptg: $1000; Ptgs: A2 Index in Ptgs: 2 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '4', label: 'B2\n$1500', color: '#31b0d5', title: 'Name: B2<br>Alias: null<br>Value: $1500<br>Type: CELL_WITH_VALUE<br>Id: 4<br>Formula Expression: Formula String: B2; Formula Values: $1500; Formula Ptg: $1500; Ptgs: B2 Index in Ptgs: 3 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '5', label: 'VALUE\n#', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: #<br>Type: CONSTANT_VALUE<br>Id: 5<br>Formula Expression: Formula String: VALUE; Formula Values: #; Formula Ptg: #; Ptgs: VALUE Index in Ptgs: 4 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '6', label: 'C2\n$1800', color: '#31b0d5', title: 'Name: C2<br>Alias: null<br>Value: $1800<br>Type: CELL_WITH_VALUE<br>Id: 6<br>Formula Expression: Formula String: C2; Formula Values: $1800; Formula Ptg: $1800; Ptgs: C2 Index in Ptgs: 5 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '7', label: 'DEFINE\nDEFINE', color: '#f0ad4e', title: 'Name: DEFINE<br>Alias: null<br>Value: DEFINE<br>Type: FUNCTION<br>Id: 7<br>Formula Expression: Formula String: DEFINE(C2, VALUE, B2, A2, VALUE); Formula Values: DEFINE($1800, #, $1500, $1000, DEVDEF_1); Formula Ptg: ; Ptgs:  Index in Ptgs: 6 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '8', label: 'D7\n$1800', color: '#31b0d5', title: 'Name: D7<br>Alias: null<br>Value: $1800<br>Type: CELL_WITH_FORMULA<br>Id: 8<br>Formula Expression: Formula String: FUNCEXEC(B2, A2, VALUE); Formula Values: FUNCEXEC($1500, $1000, DEVDEF_1); Formula Ptg: ; Ptgs:  Index in Ptgs: 0 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '10', label: 'VALUE\nDEVDEF_1', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: DEVDEF_1<br>Type: CONSTANT_VALUE<br>Id: 10<br>Formula Expression: Formula String: VALUE; Formula Values: DEVDEF_1; Formula Ptg: DEVDEF_1; Ptgs: VALUE Index in Ptgs: 1 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '11', label: 'A2\n$1000', color: '#31b0d5', title: 'Name: A2<br>Alias: null<br>Value: $1000<br>Type: CELL_WITH_VALUE<br>Id: 11<br>Formula Expression: Formula String: A2; Formula Values: $1000; Formula Ptg: $1000; Ptgs: A2 Index in Ptgs: 2 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '12', label: 'B2\n$1500', color: '#31b0d5', title: 'Name: B2<br>Alias: null<br>Value: $1500<br>Type: CELL_WITH_VALUE<br>Id: 12<br>Formula Expression: Formula String: B2; Formula Values: $1500; Formula Ptg: $1500; Ptgs: B2 Index in Ptgs: 3 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '13', label: 'FUNCEXEC\n$1800', color: '#f0ad4e', title: 'Name: FUNCEXEC<br>Alias: null<br>Value: $1800<br>Type: FUNCTION<br>Id: 13<br>Formula Expression: Formula String: FUNCEXEC(B2, A2, VALUE); Formula Values: FUNCEXEC($1500, $1000, DEVDEF_1); Formula Ptg: ; Ptgs:  Index in Ptgs: 4 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '14', label: 'A8\nDEFINE', color: '#31b0d5', title: 'Name: A8<br>Alias: null<br>Value: DEFINE<br>Type: CELL_WITH_FORMULA<br>Id: 14<br>Formula Expression: Formula String: DEFINE(C3, VALUE, B3, A3, VALUE); Formula Values: DEFINE($1801, #, $1501, $1001, DEVDEF_2); Formula Ptg: ; Ptgs:  Index in Ptgs: 0 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '16', label: 'VALUE\nDEVDEF_2', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: DEVDEF_2<br>Type: CONSTANT_VALUE<br>Id: 16<br>Formula Expression: Formula String: VALUE; Formula Values: DEVDEF_2; Formula Ptg: DEVDEF_2; Ptgs: VALUE Index in Ptgs: 1 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '17', label: 'A3\n$1001', color: '#31b0d5', title: 'Name: A3<br>Alias: null<br>Value: $1001<br>Type: CELL_WITH_VALUE<br>Id: 17<br>Formula Expression: Formula String: A3; Formula Values: $1001; Formula Ptg: $1001; Ptgs: A3 Index in Ptgs: 2 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '18', label: 'B3\n$1501', color: '#31b0d5', title: 'Name: B3<br>Alias: null<br>Value: $1501<br>Type: CELL_WITH_VALUE<br>Id: 18<br>Formula Expression: Formula String: B3; Formula Values: $1501; Formula Ptg: $1501; Ptgs: B3 Index in Ptgs: 3 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '19', label: 'VALUE\n#', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: #<br>Type: CONSTANT_VALUE<br>Id: 19<br>Formula Expression: Formula String: VALUE; Formula Values: #; Formula Ptg: #; Ptgs: VALUE Index in Ptgs: 4 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '20', label: 'C3\n$1801', color: '#31b0d5', title: 'Name: C3<br>Alias: null<br>Value: $1801<br>Type: CELL_WITH_VALUE<br>Id: 20<br>Formula Expression: Formula String: C3; Formula Values: $1801; Formula Ptg: $1801; Ptgs: C3 Index in Ptgs: 5 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '21', label: 'DEFINE\nDEFINE', color: '#f0ad4e', title: 'Name: DEFINE<br>Alias: null<br>Value: DEFINE<br>Type: FUNCTION<br>Id: 21<br>Formula Expression: Formula String: DEFINE(C3, VALUE, B3, A3, VALUE); Formula Values: DEFINE($1801, #, $1501, $1001, DEVDEF_2); Formula Ptg: ; Ptgs:  Index in Ptgs: 6 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '22', label: 'D8\n$1801', color: '#31b0d5', title: 'Name: D8<br>Alias: null<br>Value: $1801<br>Type: CELL_WITH_FORMULA<br>Id: 22<br>Formula Expression: Formula String: FUNCEXEC(B3, A3, VALUE); Formula Values: FUNCEXEC($1501, $1001, DEVDEF_2); Formula Ptg: ; Ptgs:  Index in Ptgs: 0 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '24', label: 'VALUE\nDEVDEF_2', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: DEVDEF_2<br>Type: CONSTANT_VALUE<br>Id: 24<br>Formula Expression: Formula String: VALUE; Formula Values: DEVDEF_2; Formula Ptg: DEVDEF_2; Ptgs: VALUE Index in Ptgs: 1 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '25', label: 'A3\n$1001', color: '#31b0d5', title: 'Name: A3<br>Alias: null<br>Value: $1001<br>Type: CELL_WITH_VALUE<br>Id: 25<br>Formula Expression: Formula String: A3; Formula Values: $1001; Formula Ptg: $1001; Ptgs: A3 Index in Ptgs: 2 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '26', label: 'B3\n$1501', color: '#31b0d5', title: 'Name: B3<br>Alias: null<br>Value: $1501<br>Type: CELL_WITH_VALUE<br>Id: 26<br>Formula Expression: Formula String: B3; Formula Values: $1501; Formula Ptg: $1501; Ptgs: B3 Index in Ptgs: 3 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '27', label: 'FUNCEXEC\n$1801', color: '#f0ad4e', title: 'Name: FUNCEXEC<br>Alias: null<br>Value: $1801<br>Type: FUNCTION<br>Id: 27<br>Formula Expression: Formula String: FUNCEXEC(B3, A3, VALUE); Formula Values: FUNCEXEC($1501, $1001, DEVDEF_2); Formula Ptg: ; Ptgs:  Index in Ptgs: 4 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '28', label: 'A9\nDEFINE', color: '#31b0d5', title: 'Name: A9<br>Alias: null<br>Value: DEFINE<br>Type: CELL_WITH_FORMULA<br>Id: 28<br>Formula Expression: Formula String: DEFINE(C4, VALUE, B4, A4, VALUE); Formula Values: DEFINE($1802, #, $1502, $1002, DEVDEF_3); Formula Ptg: ; Ptgs:  Index in Ptgs: 0 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '30', label: 'VALUE\nDEVDEF_3', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: DEVDEF_3<br>Type: CONSTANT_VALUE<br>Id: 30<br>Formula Expression: Formula String: VALUE; Formula Values: DEVDEF_3; Formula Ptg: DEVDEF_3; Ptgs: VALUE Index in Ptgs: 1 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '31', label: 'A4\n$1002', color: '#31b0d5', title: 'Name: A4<br>Alias: null<br>Value: $1002<br>Type: CELL_WITH_VALUE<br>Id: 31<br>Formula Expression: Formula String: A4; Formula Values: $1002; Formula Ptg: $1002; Ptgs: A4 Index in Ptgs: 2 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '32', label: 'B4\n$1502', color: '#31b0d5', title: 'Name: B4<br>Alias: null<br>Value: $1502<br>Type: CELL_WITH_VALUE<br>Id: 32<br>Formula Expression: Formula String: B4; Formula Values: $1502; Formula Ptg: $1502; Ptgs: B4 Index in Ptgs: 3 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '33', label: 'VALUE\n#', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: #<br>Type: CONSTANT_VALUE<br>Id: 33<br>Formula Expression: Formula String: VALUE; Formula Values: #; Formula Ptg: #; Ptgs: VALUE Index in Ptgs: 4 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '34', label: 'C4\n$1802', color: '#31b0d5', title: 'Name: C4<br>Alias: null<br>Value: $1802<br>Type: CELL_WITH_VALUE<br>Id: 34<br>Formula Expression: Formula String: C4; Formula Values: $1802; Formula Ptg: $1802; Ptgs: C4 Index in Ptgs: 5 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '35', label: 'DEFINE\nDEFINE', color: '#f0ad4e', title: 'Name: DEFINE<br>Alias: null<br>Value: DEFINE<br>Type: FUNCTION<br>Id: 35<br>Formula Expression: Formula String: DEFINE(C4, VALUE, B4, A4, VALUE); Formula Values: DEFINE($1802, #, $1502, $1002, DEVDEF_3); Formula Ptg: ; Ptgs:  Index in Ptgs: 6 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '36', label: 'D9\n$1802', color: '#31b0d5', title: 'Name: D9<br>Alias: null<br>Value: $1802<br>Type: CELL_WITH_FORMULA<br>Id: 36<br>Formula Expression: Formula String: FUNCEXEC(B4, A4, VALUE); Formula Values: FUNCEXEC($1502, $1002, DEVDEF_3); Formula Ptg: ; Ptgs:  Index in Ptgs: 0 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '38', label: 'VALUE\nDEVDEF_3', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: DEVDEF_3<br>Type: CONSTANT_VALUE<br>Id: 38<br>Formula Expression: Formula String: VALUE; Formula Values: DEVDEF_3; Formula Ptg: DEVDEF_3; Ptgs: VALUE Index in Ptgs: 1 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '39', label: 'A4\n$1002', color: '#31b0d5', title: 'Name: A4<br>Alias: null<br>Value: $1002<br>Type: CELL_WITH_VALUE<br>Id: 39<br>Formula Expression: Formula String: A4; Formula Values: $1002; Formula Ptg: $1002; Ptgs: A4 Index in Ptgs: 2 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '40', label: 'B4\n$1502', color: '#31b0d5', title: 'Name: B4<br>Alias: null<br>Value: $1502<br>Type: CELL_WITH_VALUE<br>Id: 40<br>Formula Expression: Formula String: B4; Formula Values: $1502; Formula Ptg: $1502; Ptgs: B4 Index in Ptgs: 3 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'},
{id: '41', label: 'FUNCEXEC\n$1802', color: '#f0ad4e', title: 'Name: FUNCEXEC<br>Alias: null<br>Value: $1802<br>Type: FUNCTION<br>Id: 41<br>Formula Expression: Formula String: FUNCEXEC(B4, A4, VALUE); Formula Values: FUNCEXEC($1502, $1002, DEVDEF_3); Formula Ptg: ; Ptgs:  Index in Ptgs: 4 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@574ebdaf'}
                            ]);


var edges = new vis.DataSet([
                             /* {from: id_a, to: id_b}, */
{from: '6', to: '7'},
{from: '5', to: '7'},
{from: '4', to: '7'},
{from: '3', to: '7'},
{from: '2', to: '7'},
{from: '7', to: '0'},
{from: '12', to: '13'},
{from: '11', to: '13'},
{from: '10', to: '13'},
{from: '13', to: '8'},
{from: '20', to: '21'},
{from: '19', to: '21'},
{from: '18', to: '21'},
{from: '17', to: '21'},
{from: '16', to: '21'},
{from: '21', to: '14'},
{from: '26', to: '27'},
{from: '25', to: '27'},
{from: '24', to: '27'},
{from: '27', to: '22'},
{from: '34', to: '35'},
{from: '33', to: '35'},
{from: '32', to: '35'},
{from: '31', to: '35'},
{from: '30', to: '35'},
{from: '35', to: '28'},
{from: '40', to: '41'},
{from: '39', to: '41'},
{from: '38', to: '41'},
{from: '41', to: '36'}
                            ]);