var nodes = new vis.DataSet([
                             /* {id: a, label: b, ...}, */
{id: '3840', label: 'C3\n$1801', color: '#31b0d5', title: 'Name: C3<br>Alias: null<br>Value: $1801<br>Type: CELL_WITH_VALUE<br>Id: 3840<br>Formula Expression: Formula String: C3; Formula Values: $1801; Formula Ptg: $1801; Ptgs: C3 Index in Ptgs: 5 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3841', label: 'DEFINE\nDEFINE', color: '#f0ad4e', title: 'Name: DEFINE<br>Alias: null<br>Value: DEFINE<br>Type: FUNCTION<br>Id: 3841<br>Formula Expression: Formula String: DEFINE(C3, VALUE, B3, A3, VALUE); Formula Values: DEFINE($1801, #, $1501, $1001, DEVDEF_2); Formula Ptg: ; Ptgs:  Index in Ptgs: 6 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3842', label: 'D8\n$1801', color: '#31b0d5', title: 'Name: D8<br>Alias: null<br>Value: $1801<br>Type: CELL_WITH_FORMULA<br>Id: 3842<br>Formula Expression: Formula String: FUNCEXEC(B3, A3, VALUE); Formula Values: FUNCEXEC($1501, $1001, DEVDEF_2); Formula Ptg: ; Ptgs:  Index in Ptgs: 0 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3844', label: 'VALUE\nDEVDEF_2', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: DEVDEF_2<br>Type: CONSTANT_VALUE<br>Id: 3844<br>Formula Expression: Formula String: VALUE; Formula Values: DEVDEF_2; Formula Ptg: DEVDEF_2; Ptgs: VALUE Index in Ptgs: 1 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3845', label: 'A3\n$1001', color: '#31b0d5', title: 'Name: A3<br>Alias: null<br>Value: $1001<br>Type: CELL_WITH_VALUE<br>Id: 3845<br>Formula Expression: Formula String: A3; Formula Values: $1001; Formula Ptg: $1001; Ptgs: A3 Index in Ptgs: 2 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3846', label: 'B3\n$1501', color: '#31b0d5', title: 'Name: B3<br>Alias: null<br>Value: $1501<br>Type: CELL_WITH_VALUE<br>Id: 3846<br>Formula Expression: Formula String: B3; Formula Values: $1501; Formula Ptg: $1501; Ptgs: B3 Index in Ptgs: 3 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3847', label: 'FUNCEXEC\n$1801', color: '#f0ad4e', title: 'Name: FUNCEXEC<br>Alias: null<br>Value: $1801<br>Type: FUNCTION<br>Id: 3847<br>Formula Expression: Formula String: FUNCEXEC(B3, A3, VALUE); Formula Values: FUNCEXEC($1501, $1001, DEVDEF_2); Formula Ptg: ; Ptgs:  Index in Ptgs: 4 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3848', label: 'A9\nDEFINE', color: '#31b0d5', title: 'Name: A9<br>Alias: null<br>Value: DEFINE<br>Type: CELL_WITH_FORMULA<br>Id: 3848<br>Formula Expression: Formula String: DEFINE(C4, VALUE, B4, A4, VALUE); Formula Values: DEFINE($1802, #, $1502, $1002, DEVDEF_3); Formula Ptg: ; Ptgs:  Index in Ptgs: 0 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3850', label: 'VALUE\nDEVDEF_3', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: DEVDEF_3<br>Type: CONSTANT_VALUE<br>Id: 3850<br>Formula Expression: Formula String: VALUE; Formula Values: DEVDEF_3; Formula Ptg: DEVDEF_3; Ptgs: VALUE Index in Ptgs: 1 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3853', label: 'VALUE\n#', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: #<br>Type: CONSTANT_VALUE<br>Id: 3853<br>Formula Expression: Formula String: VALUE; Formula Values: #; Formula Ptg: #; Ptgs: VALUE Index in Ptgs: 4 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3854', label: 'C4\n$1802', color: '#31b0d5', title: 'Name: C4<br>Alias: null<br>Value: $1802<br>Type: CELL_WITH_VALUE<br>Id: 3854<br>Formula Expression: Formula String: C4; Formula Values: $1802; Formula Ptg: $1802; Ptgs: C4 Index in Ptgs: 5 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3855', label: 'DEFINE\nDEFINE', color: '#f0ad4e', title: 'Name: DEFINE<br>Alias: null<br>Value: DEFINE<br>Type: FUNCTION<br>Id: 3855<br>Formula Expression: Formula String: DEFINE(C4, VALUE, B4, A4, VALUE); Formula Values: DEFINE($1802, #, $1502, $1002, DEVDEF_3); Formula Ptg: ; Ptgs:  Index in Ptgs: 6 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3856', label: 'D9\n$1802', color: '#31b0d5', title: 'Name: D9<br>Alias: null<br>Value: $1802<br>Type: CELL_WITH_FORMULA<br>Id: 3856<br>Formula Expression: Formula String: FUNCEXEC(B4, A4, VALUE); Formula Values: FUNCEXEC($1502, $1002, DEVDEF_3); Formula Ptg: ; Ptgs:  Index in Ptgs: 0 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3858', label: 'VALUE\nDEVDEF_3', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: DEVDEF_3<br>Type: CONSTANT_VALUE<br>Id: 3858<br>Formula Expression: Formula String: VALUE; Formula Values: DEVDEF_3; Formula Ptg: DEVDEF_3; Ptgs: VALUE Index in Ptgs: 1 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3859', label: 'A4\n$1002', color: '#31b0d5', title: 'Name: A4<br>Alias: null<br>Value: $1002<br>Type: CELL_WITH_VALUE<br>Id: 3859<br>Formula Expression: Formula String: A4; Formula Values: $1002; Formula Ptg: $1002; Ptgs: A4 Index in Ptgs: 2 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3860', label: 'B4\n$1502', color: '#31b0d5', title: 'Name: B4<br>Alias: null<br>Value: $1502<br>Type: CELL_WITH_VALUE<br>Id: 3860<br>Formula Expression: Formula String: B4; Formula Values: $1502; Formula Ptg: $1502; Ptgs: B4 Index in Ptgs: 3 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3861', label: 'FUNCEXEC\n$1802', color: '#f0ad4e', title: 'Name: FUNCEXEC<br>Alias: null<br>Value: $1802<br>Type: FUNCTION<br>Id: 3861<br>Formula Expression: Formula String: FUNCEXEC(B4, A4, VALUE); Formula Values: FUNCEXEC($1502, $1002, DEVDEF_3); Formula Ptg: ; Ptgs:  Index in Ptgs: 4 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3820', label: 'A7\nDEFINE', color: '#31b0d5', title: 'Name: A7<br>Alias: null<br>Value: DEFINE<br>Type: CELL_WITH_FORMULA<br>Id: 3820<br>Formula Expression: Formula String: DEFINE(C2, VALUE, B2, A2, VALUE); Formula Values: DEFINE($1800, #, $1500, $1000, DEVDEF_1); Formula Ptg: ; Ptgs:  Index in Ptgs: 0 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3822', label: 'VALUE\nDEVDEF_1', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: DEVDEF_1<br>Type: CONSTANT_VALUE<br>Id: 3822<br>Formula Expression: Formula String: VALUE; Formula Values: DEVDEF_1; Formula Ptg: DEVDEF_1; Ptgs: VALUE Index in Ptgs: 1 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3824', label: 'B2\n$1500', color: '#31b0d5', title: 'Name: B2<br>Alias: null<br>Value: $1500<br>Type: CELL_WITH_VALUE<br>Id: 3824<br>Formula Expression: Formula String: B2; Formula Values: $1500; Formula Ptg: $1500; Ptgs: B2 Index in Ptgs: 3 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3825', label: 'VALUE\n#', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: #<br>Type: CONSTANT_VALUE<br>Id: 3825<br>Formula Expression: Formula String: VALUE; Formula Values: #; Formula Ptg: #; Ptgs: VALUE Index in Ptgs: 4 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3826', label: 'C2\n$1800', color: '#31b0d5', title: 'Name: C2<br>Alias: null<br>Value: $1800<br>Type: CELL_WITH_VALUE<br>Id: 3826<br>Formula Expression: Formula String: C2; Formula Values: $1800; Formula Ptg: $1800; Ptgs: C2 Index in Ptgs: 5 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3827', label: 'DEFINE\nDEFINE', color: '#f0ad4e', title: 'Name: DEFINE<br>Alias: null<br>Value: DEFINE<br>Type: FUNCTION<br>Id: 3827<br>Formula Expression: Formula String: DEFINE(C2, VALUE, B2, A2, VALUE); Formula Values: DEFINE($1800, #, $1500, $1000, DEVDEF_1); Formula Ptg: ; Ptgs:  Index in Ptgs: 6 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3828', label: 'D7\n$1800', color: '#31b0d5', title: 'Name: D7<br>Alias: null<br>Value: $1800<br>Type: CELL_WITH_FORMULA<br>Id: 3828<br>Formula Expression: Formula String: FUNCEXEC(B2, A2, VALUE); Formula Values: FUNCEXEC($1500, $1000, DEVDEF_1); Formula Ptg: ; Ptgs:  Index in Ptgs: 0 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3830', label: 'VALUE\nDEVDEF_1', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: DEVDEF_1<br>Type: CONSTANT_VALUE<br>Id: 3830<br>Formula Expression: Formula String: VALUE; Formula Values: DEVDEF_1; Formula Ptg: DEVDEF_1; Ptgs: VALUE Index in Ptgs: 1 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3831', label: 'A2\n$1000', color: '#31b0d5', title: 'Name: A2<br>Alias: null<br>Value: $1000<br>Type: CELL_WITH_VALUE<br>Id: 3831<br>Formula Expression: Formula String: A2; Formula Values: $1000; Formula Ptg: $1000; Ptgs: A2 Index in Ptgs: 2 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3833', label: 'FUNCEXEC\n$1800', color: '#f0ad4e', title: 'Name: FUNCEXEC<br>Alias: null<br>Value: $1800<br>Type: FUNCTION<br>Id: 3833<br>Formula Expression: Formula String: FUNCEXEC(B2, A2, VALUE); Formula Values: FUNCEXEC($1500, $1000, DEVDEF_1); Formula Ptg: ; Ptgs:  Index in Ptgs: 4 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3834', label: 'A8\nDEFINE', color: '#31b0d5', title: 'Name: A8<br>Alias: null<br>Value: DEFINE<br>Type: CELL_WITH_FORMULA<br>Id: 3834<br>Formula Expression: Formula String: DEFINE(C3, VALUE, B3, A3, VALUE); Formula Values: DEFINE($1801, #, $1501, $1001, DEVDEF_2); Formula Ptg: ; Ptgs:  Index in Ptgs: 0 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3836', label: 'VALUE\nDEVDEF_2', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: DEVDEF_2<br>Type: CONSTANT_VALUE<br>Id: 3836<br>Formula Expression: Formula String: VALUE; Formula Values: DEVDEF_2; Formula Ptg: DEVDEF_2; Ptgs: VALUE Index in Ptgs: 1 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'},
{id: '3839', label: 'VALUE\n#', color: '#31b0d5', title: 'Name: VALUE<br>Alias: null<br>Value: #<br>Type: CONSTANT_VALUE<br>Id: 3839<br>Formula Expression: Formula String: VALUE; Formula Values: #; Formula Ptg: #; Ptgs: VALUE Index in Ptgs: 4 <br>Source Object Id: com.dataart.spreadsheetanalytics.engine.PoiProxyWorkbook@dbcf7c3'}
                            ]);


var edges = new vis.DataSet([
                             /* {from: id_a, to: id_b}, */
{from: '3826', to: '3827'},
{from: '3840', to: '3841'},
{from: '3846', to: '3847'},
{from: '3854', to: '3855'},
{from: '3860', to: '3861'},
{from: '3824', to: '3827'},
{from: '3830', to: '3833'},
{from: '3844', to: '3847'},
{from: '3858', to: '3861'},
{from: '3822', to: '3827'},
{from: '3836', to: '3841'},
{from: '3850', to: '3855'},
{from: '3824', to: '3833'},
{from: '3827', to: '3820'},
{from: '3841', to: '3834'},
{from: '3855', to: '3848'},
{from: '3831', to: '3827'},
{from: '3845', to: '3841'},
{from: '3859', to: '3855'},
{from: '3833', to: '3828'},
{from: '3847', to: '3842'},
{from: '3861', to: '3856'},
{from: '3825', to: '3827'},
{from: '3831', to: '3833'},
{from: '3839', to: '3841'},
{from: '3845', to: '3847'},
{from: '3853', to: '3855'},
{from: '3859', to: '3861'},
{from: '3846', to: '3841'},
{from: '3860', to: '3855'}
                            ]);